[package]
name = "puck"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "Dynamically structured notes"
repository = "https://github.com/trippwill/puck"

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.4", default-features = false, features = ["tracing"] }
i18n-embed = { version = "0.16", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
open = "5.3.2"
rust-embed = "8.8.0"
thiserror = "2.0.19"
time = "0.3.55"
tokio = { version = "1.48.0", features = ["full"] }
tokio-rusqlite = { git = "https://github.com/trippwill/tokio-rusqlite.git", tag = "v0.7.0-0.40.1", version = "0.7.0", features = ["bundled", "uuid", "time", "backup"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = { version = "1.24.0", features = ["v7"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
# See https://github.com/pop-os/libcosmic/blob/master/Cargo.toml for available features.
# Remove features if not needed.
features = [
    # About widget for the app
    "about",
    # On app startup, focuses an existing instance if the app is already open
    "single-instance",
    # Markdown widget
    "markdown",
    # QR code widget
    "qr_code",
    # GPU-accelerated rendering
    "wgpu",
    # xdg portal dialogs on Linux
    "xdg-portal"
]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
